### ISSUE TITLE
Cannot read property 'users' of undefined

### ISSUE THREAD

**Issue by Oxtaviox** [everyone-bot/everyone-bot#27]
Im hosting the bot by myselft, but when someone tries to run the command / EVERYONE it pops this message in the CMD, and nothing happens in the group chat
![Captura](https://user-images.githubusercontent.com/37225494/89485814-976bfd80-d76f-11ea-8063-119b1ac53f06.JPG)
:

TypeError: Cannot read property 'users' of undefined
    at C:\Program Files (x86)\everyone-bot-master\controllers\everyoneController.js:20:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
HTTPError: Response code 403 (Forbidden)
    at onResponse (C:\Program Files (x86)\everyone-bot-master\node_modules\got\dist\source\as-promise\index.js:142:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

How can i solve it?

**Comment by aquibm** [comment]
Heya, have you got a [firebase](http://firebase.com/) instance setup and configured the db access?

**Comment by aquibm** [comment]
Closing due to inactivity - please feel free to re-open the issue if you're still having problems
